update from dev branch

diff --git a/.github/workflows/test-build-cmake-dot-config.yml b/.github/workflows/test-build-cmake-dot-config.yml
--- a/.github/workflows/test-build-cmake-dot-config.yml
+++ b/.github/workflows/test-build-cmake-dot-config.yml
@@ -1,11 +1,11 @@
-name: wolfboot CMake Script
+name: wolfboot CMake (.config)
 on:
   push:
     branches: [ '*' ]
   pull_request:
     branches: [ '*' ]
 jobs:
-  wolfboot_build_script_test:
+  wolfboot_dot_config_test:
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
@@ -62,15 +62,41 @@ jobs:
 
       - name: Install requirements
         run: |
-          sudo apt-get update
-          sudo apt-get install -y gcc-arm-none-eabi gcc-powerpc-linux-gnu cmake
+            # Run system updates and install toolchain
+            sudo apt-get update
+            sudo apt-get install -y gcc-arm-none-eabi gcc-powerpc-linux-gnu cmake
 
-      - name: Run wolfboot_build script
+      - name: Run dot-config examples
         run: |
-          rm -rf ./build
+            # Sample .config cmake test
 
-          ./tools/scripts/wolfboot_build.sh --CLEAN  "stm32l4"
-          ./tools/scripts/wolfboot_build.sh --target "stm32l4"
+            set -euo pipefail
 
-          ./tools/scripts/wolfboot_build.sh --CLEAN  "stm32g0"
-          ./tools/scripts/wolfboot_build.sh --target "stm32g0"
+            LOG_FILE="run.log"
+            KEYWORD="Config mode: dot"
+            echo "Saving output to $LOG_FILE"
+
+            echo "Fetch stm32h7 example .config"
+            cp   ./config/examples/stm32h7.config ./.config
+            ls   .config
+            cat  .config
+            echo ""
+
+            echo "Clean"
+            rm -rf ./build-stm32h7
+
+            # Here we should see the .config file values read and displayed:
+            cmake -S . -B build-stm32h7 \
+              -DUSE_DOT_CONFIG=ON       \
+              -DWOLFBOOT_TARGET=stm32h7 2>&1 | tee "$LOG_FILE"
+
+            # Config dot-config mode
+            if grep -q -- "$KEYWORD" "$LOG_FILE"; then
+                echo "Keyword found: $KEYWORD"
+            else
+                echo "Keyword not found: $KEYWORD" >&2
+                exit 1
+            fi
+
+            # Sample build
+            cmake --build build-stm32h7 -j
